###############################################################
# Author      : Jerzy 'Yuri' Kramarz (op7ic)                  #
# Version     : 1.0                                           #
# Type        : Terraform/Ansible                             #
# Description : Cloud-Investigate. See README.md for details  # 
# License     : See LICENSE for details                       #   
###############################################################




############################################################
# Install autopsy. Tag: autopsy                            # 
############################################################
--- 
- name: Attempt to deploy autopsy. Fail and repeat if needed.
  block:
    - name: set fact
      set_fact:
        include_autopsy_installer_counter: "{{ 0 if include_autopsy_installer_counter is undefined else include_autopsy_installer_counter|default(0)|int + 1 }}"
      tags: autopsy
  
    - name: Domain configuration file
      include_vars:
        file: ../../../../config/os-setup.yml
        name: config_file
      tags: autopsy
      
    - name: Read Config File and get credentials
      set_fact:
        ansible_user: "{{ config_file.local_admin_credentials.username }}"
        ansible_password: "{{ config_file.local_admin_credentials.password }}"
      tags: autopsy

    - name: Gather remote facts
      setup: {}
      tags: autopsy
      
    # AWS somehow is a lot slower than azure so we might need to wait longer for this to work
    # This check will pool until we get successful connection before moving on to other work
    - name: Check if we can connect with the default username and password
      ansible.builtin.wait_for_connection:
        connect_timeout: 10
        timeout: 500
        delay: 5
        sleep: 5
      register: connection
      ignore_errors: yes
      vars:
        ansible_user: "{{ ansible_user }}"
        ansible_pass: "{{ ansible_password }}"
      tags: autopsy
      
    - name: Print results
      debug:
        msg: "Connection {% if connection.failed %}failed{% else %}succeeded{% endif %}"
      tags: autopsy
      
    # Meta is used to ensure that if connection fails that reconnect works.
    # Since baseline is first task to run this show, any fail here should be clared for restart
    - meta: clear_host_errors
      tags: autopsy 
      
    - name: Test for autopsy executable and install
      ansible.windows.win_package:
        path: "{{ config_file.tools.installers.autopsy }}"
        arguments: /q
        state: present
      register: autopsy_executable
      tags: autopsy
            
  rescue:
    - include_tasks: 
        file: roles/autopsy/tasks/main.yml
        apply:
          tags:
            - autopsy
      when: include_autopsy_installer_counter|int < include_max|default(10)|int
      tags: autopsy
      
    - fail:
        msg: Failed to install autopsy after 10 attempts
      when: include_autopsy_installer_counter|int >= include_max|default(10)|int
      tags: autopsy
  tags: autopsy