###############################################################
# Author      : Jerzy 'Yuri' Kramarz (op7ic)                  #
# Version     : 1.0                                           #
# Type        : Terraform/Ansible                             #
# Description : Cloud-Investigate. See README.md for details  # 
# License     : See LICENSE for details                       #   
###############################################################

---
- name: Configure forensic server
  hosts: all
  gather_facts: no
  roles:
  - role: baseline
    tags: [ baseline ]
  - role: diskpart
    tags: [ diskpart ]
  - role: chocoladey
    tags: [ chocoladey ]
  - role: wsl2
    tags: [ wsl2 ]
  - role: autopsy
    tags: [ autopsy ]
  - role: tools
    tags: [ tools ]
  - role: kape
    tags: [ kape ]
  - role: sysmon
    tags: [ symon ]
  - role: monitoring
    tags: [ monitoring ]
